name: Compil
on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    name: "pytest"
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
      - uses: davidslusser/actions_python_pytest@v1.0.1
        with:
          src: "script/mysystem"
          options: "-v"
          pip_install_command: "pip install ifaddr psutil pytest pytest-cov"
      - run: |
            coverage run -m pytest
            coverage report
            coverage xml
      - name: Get Cover 
        uses: orgoro/coverage@v3.2
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
