name: sysinfo CI

on:
  push:
    branches:
      - 'feature/**'
    paths:
      - 'src/sysinfo.c'
    tags:
      - 'v*.*.*'

jobs:
  C-lint-sysinfo:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/feature/')
    steps:
      - name: sysinfo checkout
        uses: actions/checkout@v6
      - name: sysinfo lint
        run: make lint

  C-compilation-sysinfo:
    runs-on: ubuntu-latest
    needs: C-lint-sysinfo
    if: startsWith(github.ref, 'refs/heads/feature/') || startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: sysinfo checkout
        uses: actions/checkout@v6
      - name: sysinfo compilation
        run: make build
      - name: Upload binary artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-artifact@v4
        with:
          name: sysinfo-binary
          path: ./sysinfo

  deploy:
    runs-on: ubuntu-latest
    needs: C-compilation-sysinfo
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
      packages: write
    steps:
      - name: sysinfo checkout
        uses: actions/checkout@v6
      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: sysinfo-binary
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: sysinfo
          draft: false
